apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: pmo14lgzs-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: pmo14lgzs-python 
  name: pmo14lgzs-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: pmo14lgzs-python 
